#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_crkbd_w(C_42(HRM(_BASE))),
	[1] = LAYOUT_crkbd_w(C_42(HRM(_COLE))),
	[2] = LAYOUT_crkbd_w(C_42(_NUMB)),
	[3] = LAYOUT_crkbd_w(C_42(_SYMB)),
	[4] = LAYOUT_crkbd_w(C_42(_FUNC))
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




